create table
  public.todos (
    id bigint generated by default as identity not null,
    user_id uuid null,
    task text null,
    is_competed boolean null default false,
    is_archived boolean null default false,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint todos_pkey primary key (id)
  ) tablespace pg_default;

